name: blog_common
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.0.0


